
language: c

sudo: true

before_install:
  - sudo apt-get install -y autotools-dev \
               bison \
               chrpath \
               cmake \
               default-jdk \
               flex \
               gfortran \
               help2man \
               latex2html \
               libboost-filesystem-dev \
               libboost-program-options-dev \
               libboost-python-dev \
               libboost-regex-dev \
               libboost-system-dev \
               libboost-test-dev \
               libboost-thread-dev \
               libcgroup-dev \
               libcurl4-openssl-dev \
               libexpat1-dev \
               libglobus-ftp-client-dev \
               libglobus-gass-server-ez-dev \
               libglobus-gram-client-dev \
               libglobus-gram-protocol-dev \
               libglobus-gss-assist-dev \
               libkrb5-dev \
               libldap2-dev \
               libpcre3-dev \
               libpq-dev \
               libvirt-dev \
               libx11-dev \
               libxml2-dev \
               libxss-dev \
               po-debconf \
               python-dev \
               texlive-font-utils \
               transfig \
               uuid-dev \
               zlib1g-dev

script: cmake -DPROPER:BOOL=ON \
              -DCLIPPED:BOOL=ON \
              -DUW_BUILD:BOOL=OFF \
              -D_DEBUG:BOOL=TRUE \
              -DCMAKE_SKIP_RPATH:BOOL=ON \
              -DHAVE_EXT_GSOAP:BOOL=OFF \
              -DWITH_GSOAP:BOOL=OFF \
              -DHAVE_EXT_CURL:BOOL=ON \
              -DHAVE_EXT_OPENSSL:BOOL=ON \
              -DHAVE_EXT_BOOST:BOOL=ON \
              -DHAVE_EXT_GLOBUS:BOOL=ON \
              -DHAVE_EXT_KRB5:BOOL=ON \
              -DHAVE_EXT_LIBVIRT:BOOL=ON \
              -DHAVE_EXT_LIBXML2:BOOL=ON \
              -DHAVE_EXT_OPENSSL:BOOL=ON \
              -DHAVE_EXT_PCRE:BOOL=ON \
              -DHAVE_EXT_VOMS:BOOL=OFF \
              -DWITH_VOMS:BOOL=OFF \
              -DWITH_LIBCGROUP:BOOL=ON \
              -DWANT_CONTRIB:BOOL=OFF \
              -DWITH_BOSCO:BOOL=OFF \
              -DWITH_PYTHON_BINDINGS:BOOL=OFF \
              -DWITH_CAMPUSFACTORY:BOOL=OFF && \
        make
